# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: TianciBlog
subtitle: 'Tianciの小窝'
description: 'Tianciの小窝,天赐个人博客,TianciBlog'
keywords: 'Tianciの小窝,天赐个人博客,TianciBlog'
author: Tianci
language: zh-cn
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: /
root: /
permalink: :category/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [404.html,photo/**] # 指定404页面跳过渲染
# skip_render: life/*.html #跳过指定文件的渲染，您可使用 glob 表达式来匹配路径

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight: 
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = 禁用分页)
# order_by: Posts order. (默认按日期降序)
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# 日期/时间格式
## Hexo使用Moment.js解析和显示日期
## 您可以自定义中定义的日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# 分页
## 将“每页”设置为0以禁用分页
per_page: 10
pagination_dir: page

# themes
theme: Sakura

#RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# 加密
encrypt: 
  password: lovetianci
